name: Changeset and Release Workflow

on:
  push:
    branches:
      - main

jobs:
  changesets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get tags
      run: git fetch --tags origin

    - name: Setup Node.js environment
      uses: actions/setup-node@v3

    - name: Install dependencies
      run: npm install 

    - name: Create Release Pull Request
      id: changesets
      uses: changesets/action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Tags
      if: steps.changesets.outputs.hasChangesets == 'false'
      run: |
          npx changeset tag && git push origin --tags

